# 导入相关库

In [14]:
import torch
import numpy as np
import pandas as pd

## 2.1.3 广播机制

1. 广播机制的工作方式：
    - 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状
    - 对生成的数组执行按元素操作
    

In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
# a 为 3×1 矩阵
# b 为 1×2 矩阵

print(a)
print(b)

# 广播机制，将两个形状不同的张量，扩展为更大的矩阵
# 扩展为 3 × 2 矩阵
print(a + b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


## 2.1.4 索引与切片

In [ ]:
X = torch.tensor(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]   
    ]
)
# 获取最后一个元素，以及第二和第三个元素
X[-1], X[1:3]

(tensor([ 9, 10, 11, 12]),
 tensor([[ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]))

In [17]:
# 通过索引指定索引将元素写入矩阵
X[1, 2] = 9

X

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  9,  8],
        [ 9, 10, 11, 12]])