# 这里是动手学深度学习Pytorch版的第一节：数据操作

## 导入相关库

In [12]:
import torch
import numpy as np
import pandas as pd

## 1.1.1 入门操作

1. 创建张量的方法:

方法|说明|参数
---|---|---
tensor|从Python列表或者Numpy数组创建张量|(data)
zeros|创建一个**全0**张量|(size)
ones|创建一个**全1**张量|(size)
empty|创建一个**未初始化**张量|(size)
rand|创建一个服从**均匀分布**的随机张量,值在[0, 1]|(size)
randn|创建一个服从**高斯分布**的随机张量,**均值为0**,**标准差为1**|(size)
arange|创建一个1维的序列张量，类似于Python的range|(start, end, step)
linspace|创建一个指定范围内等间隔的序列张量|(strat, end, steps)
eye|创建一个单位矩阵（只有对角线为1，其他全为0）|(size)
from_numpy|将NumPy数组转换为张量|(ndarray)

2. 张量的属性:

属性|说明
---|---
shape|获取张量的形状
size()|获取张量的形状
dtype|获取张量的数据类型
device|查看张量所在的设备
dim()|获取张量的维度
requires_grad|是否启用梯度计算
numel()|获取张量中的元素总数
is_cuda|检查张量是否在GPU上
T|获取张量的转置
item()|获取张量的值
is_contiguous()|检查张量是否连续存储

In [13]:
# 创建行向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
# 通过张量的shape属性查看形状
x.shape

torch.Size([12])

In [15]:
# 检查张量中的元素的总数
x.numel()

12

In [16]:
# 将行向量修改为3行4列的矩阵
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [17]:
# 创建全零张量
zerostensor = torch.zeros((2, 3, 4))
print(zerostensor)

# 创建全一张量
onestensor = torch.ones((2, 3, 4))
print(onestensor)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


## 张量每个元素从均值为0，标准差为1的标准高斯分布中随机采样:

In [18]:
torch.randn(3, 4)

tensor([[ 1.6796, -1.1711, -1.0663, -0.5658],
        [-0.4283,  0.1504, -0.9688,  0.3361],
        [-0.5437, -0.2212, -0.5857,  0.9704]])

In [19]:
# 使用python列表创建张量的元素中的确定值
torch.tensor([
    [
    1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
    ])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 1.1.2 运算符

3. 张量的操作：

操作|说明
---|---
+.-.*./.**|元素级别的加减乘除以及乘方运算
matmul|矩阵乘法
dot|**向量**点积(仅适用于一维张量)
sum|求和
mean|求均值
max|求最大值
min|求最小值
argmax(x, dim)|返回最大值的索引（指定维度）
softmax(x, dim)|计算softmax（指定维度）

In [20]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print(x+y)

print(x-y)

print(x*y)

print(x/y)  

print(x**y)

tensor([ 3,  4,  6, 10])
tensor([-1,  0,  2,  6])
tensor([ 2,  4,  8, 16])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1,  4, 16, 64])


In [21]:
# 求e的x次方
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [22]:
# 对张量中的所有元素求和，会产生一个单元素张量
X.sum()

tensor(66)

4. 张量的形状操作:

操作|说明
---|---
view(shape)|改变张量的形状(不改变数据)
reshape(shape)|类似于view但更灵活
t()|转置矩阵
unsqueeze(dim)|在指定维度添加一个维度
squeeze(dim)|去掉指定维度为1的维度
cat((x, y), dim)|连接多个张量

In [23]:

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# cat方法将指定维度连接成多个张量。
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))